# Generated by Django 5.2 on 2026-01-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cot_for_stem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='raw_text',
            field=models.JSONField(),
        ),
    ]
